package:
  name: scikit-garden
  version: "0.1"

source:
  git_url: https://github.com/scikit-garden/scikit-garden

build:
  number: 0

requirements:
  build:
    - python
    - numpy>=1.16
    - scipy
    - cython>=0.28
    - scikit-learn
  run:
    - cython
    - numpy>=1.16
    - scipy
    - scikit-learn

about:
  home: https://github.com/scikit-garden/scikit-garden
  license: GPLv3
  summary: A garden for Scikit-Learn compatible decision trees and forests.
