package:
  name: mess
  version: "0.1.1"

source:
  git_url: https://github.com/messDiv/MESS
  git_tag: master

build:
  number: 11
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - msprime
    - ipyparallel >=6.0.2
    - scipy >=0.16
    - cython
    - cloudpickle
    - ipython
    - numpy
    - pandas
    - svgwrite
    - mpmath
    - certifi
    - rpy2
    - boruta_py
    - scikit-garden
  run:
    - python >=3.7
    - cloudpickle
    - setuptools
    - ipython >=5.0.0
    - ipyparallel >=6.0.2
    - cython
    - scipy >=0.16
    - nbconvert
    - joblib
    - jupyter_client
    - jupyter
    - notebook >=5.0
    - pandas
    - msprime
    - mpmath
    - rpy2 >=3.0
    - matplotlib
    - boruta_py
    - scikit-garden
    - tzlocal
    - matplotlib
    - imagemagick
    - seaborn

  commands:
    - MESS -v

about:
  home: https://github.com/messDiv/MESS
  license: GPLv3
  summary: Massive Eco-Evolutionary Synthesis Simulations
