package:
  name: macroeco
  version: "1.0.1"

source:
  git_url: https://github.com/jkitzes/macroeco/

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - decorator
    - configparser
    - mpmath
    - matplotlib
    - pandas
    - numpy
    - scipy
  run:
    - pandas
    - numpy >=1.7
    - scipy
    - matplotlib
    - decorator
    - configparser
    - mpmath

about:
  home: https://github.com/jkitzes/macroeco/
  license: GPLv3
  summary: Ecological pattern analysis in Python
