package:
  name: boruta_py
  version: "0.1.5"

source:
  git_url: https://github.com/scikit-learn-contrib/boruta_py

build:
  number: 0

requirements:
  build:
    - python
    - numpy>=1.16
    - scipy
    - cython>=0.28
    - scikit-learn
    - joblib
  run:
    - cython
    - numpy>=1.16
    - scipy
    - scikit-learn

about:
  home: https://github.com/scikit-learn-contrib/boruta_py
  license: GPLv3
  summary: Python implementations of the Boruta all-relevant feature selection method.
