package:
  name: boruta_py
  version: "0.1.5"

source:
  git_url: https://github.com/scikit-learn-contrib/boruta_py

build:
  number: 0

requirements:
  build:
    - python>=3.5
    - scipy>=0.17.0
    - scikit-learn>=0.17.1
    - joblib>=0.11
  run:
    - python>=3.5
    - numpy>=1.16.4
    - scipy>=1.3.0
    - cython>=0.28
    - scikit-learn>=0.21.2
    - joblib>=0.11

about:
  home: https://github.com/scikit-learn-contrib/boruta_py
  license: GPLv3
  summary: Python implementations of the Boruta all-relevant feature selection method.
